### PR TITLE
Version to use the refresh token mechanism since generated tokens via…

### PR DESCRIPTION
**Pull request by jlerebours**
This is a modified version to use the refresh token mechanism since dropbox removed the ability to generate some in their app console interface.
So if we want long-lived token, we now have to use a refresh tokenand there is not interface in dropbox app console to do it.

So in this commit :
* In case of run in cli mode (python dbync ...) things are automated, user just has to input the access code by following the url provided. App will then run by using refresh token retrieved via dropbox API (and print it for further use) 
* In case of docker run, user will have to generate it manually by using provided script and then set as environment variable. I also added appKey and appSecret which are required to refresh the token after the 4 hours ttl of regular token.

Hope this can help people like me just wanting some dropbox sync via one Application and not the full account sync.

### CODE REVIEW

**Comment by rbonghi** [comment]
Hi @jlerebours!

First of all, thank you very much! I really appreciate it!
I see there is a bug in my old CI, I was not updating this project for ages!

I merge this PR and fix my CI

**Review by rbonghi — APPROVED** [review]

**Comment by rbonghi** [comment]
All fixed!

**Comment by jlerebours** [comment]
Nice ! Thanks
Will you push the docker since CI failed ?
So I can switch back to your docker and not my temporary one

**Comment by rbonghi** [comment]
I made a new tag for the old release called `rbonghi/dropbox:1.0.0`

Let me know if everything works on this docker and I push, otherwise feel free to make a new PR :-)

**Comment by jlerebours** [comment]
> I made a new tag for the old release called `rbonghi/dropbox:1.0.0`
> 
> Let me know if everything works on this docker and I push, otherwise feel free to make a new PR :-)

That's good to me, running as expected for a few days now.
Thanks

**Comment by rbonghi** [comment]
Thank you @jlerebours,

I release a new version **1.1.0** and  now the `rbonghi/dropbox:latest` is up to date

**Pull request merged**
